name: C++ CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install C++ build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build using Makefile
      run: make

    - name: Run binary
      run: ./hello

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello-binary
        path: hello

